/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.Categoria;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
import negocio.ArticuloControl;

import negocio.CategoriaControl;

/**
 *
 * @author lanister
 */
public class InternalFrameArticulo extends javax.swing.JInternalFrame {

    private final ArticuloControl control;
    private String accion;
    private String id, nombreAnt;
    private String imagen = "";
    private String imagenAnt;
    private String rutaOrigen;
    private String rutaDestino;
    private final String DIRECTORIO = "src/main/java/files/articulos/";

    private int totalPorPagina = 10;
    private int numPagina = 1;
    private boolean primeraCarga = true;
    private int totalRegistros;

    public InternalFrameArticulo() {
        initComponents();

        this.control = new ArticuloControl();
        this.accion = "NUEVO";
        this.tabCrud.setEnabledAt(1, false);
        this.btnEditar.setEnabled(false);
        this.btnActivar.setEnabled(false);
        this.btnDesactivar.setEnabled(false);
        this.paginar();
        textBuscar.requestFocus();
        this.listar("",false);
        this.primeraCarga =false;
        this.cargarCategorias();
        this.listenerEdit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabCrud = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        textBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        labelTotalRegistros = new javax.swing.JLabel();
        btnAccion = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cboNumPagina = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboTotalPorPagina = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<Categoria>();
        jLabel5 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textStock = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnSubir = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 235, 240));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Articulos");
        setToolTipText("");

        jPanel1.setPreferredSize(new java.awt.Dimension(580, 450));

        jLabel1.setText("Nombre");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setRowHeight(25);
        jScrollPane1.setViewportView(tabla);

        labelTotalRegistros.setText("Registros :");

        btnAccion.setText("Nuevo");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        jLabel9.setText("# Página");

        cboNumPagina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNumPaginaItemStateChanged(evt);
            }
        });

        jLabel10.setText("Total");

        cboTotalPorPagina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "10", "20", "30", "40", "50", "100" }));
        cboTotalPorPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTotalPorPaginaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboNumPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(cboTotalPorPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar)
                    .addComponent(btnAccion)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboNumPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboTotalPorPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActivar)
                    .addComponent(btnDesactivar)
                    .addComponent(labelTotalRegistros))
                .addGap(17, 17, 17))
        );

        tabCrud.addTab("Listado", jPanel1);

        jLabel2.setText("Nombre (*)");

        jLabel3.setText("Descripcion");

        textDescripcion.setColumns(20);
        textDescripcion.setRows(5);
        jScrollPane2.setViewportView(textDescripcion);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria(*)");

        jLabel5.setText("Codigo(*)");

        jLabel6.setText("Precio(*)");

        textStock.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel7.setText("Stock(*)");

        textPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel8.setText("Imagen");

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("---producto--- ");
        lblImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSubir.setText("Seleccionar");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textNombre)
                            .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textCodigo)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubir))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(textStock, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubir))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabCrud.addTab("Registro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCrud)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:  
        this.listar(textBuscar.getText(),false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        // TODO add your handling code here:
        this.tabCrud.setEnabledAt(0, false);
        this.tabCrud.setEnabledAt(1, true);
        this.tabCrud.setSelectedIndex(1);
        this.accion = "NUEVO";

        this.limpiarFormulario();

    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:

        this.tabCrud.setEnabledAt(1, false);
        this.tabCrud.setEnabledAt(0, true);
        this.tabCrud.setSelectedIndex(0);
        this.limpiarFormulario();
        this.tabla.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        if (this.textCodigo.getText().length() == 0) {
            this.mensajeWarning("El campo Codigo es obligatorio.");
            this.textCodigo.requestFocus();
            return;
        }
        if (this.textNombre.getText().length() == 0) {
            this.mensajeWarning("El campo nombre es obligatorio.");
            this.textNombre.requestFocus();
            return;
        }

        if (this.textNombre.getText().length() > 100) {
            this.mensajeWarning("El campo nombre es demasiado largo, max = 100 caracteres.");
            this.textNombre.requestFocus();
            return;
        }

        if (this.textStock.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un stock del artículo, es obligatorio.", "Sistema", JOptionPane.WARNING_MESSAGE);
            this.textStock.requestFocus();
            return;
        }
        if (this.textPrecio.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un precio de venta, es obligatorio.", "Sistema", JOptionPane.WARNING_MESSAGE);
            textPrecio.requestFocus();
            return;
        }
        if (this.textDescripcion.getText().length() > 255) {
            this.mensajeWarning("El campo descripcion es demaciado largo, max = 255 caracteres.");
            this.textDescripcion.requestFocus();
            return;
        }

        String res = "";
        if (this.accion.equals("EDITAR")) {
            String imagenActual = "";
            if (this.imagen.equals("")) {
                imagenActual = this.imagenAnt;
            } else {
                imagenActual = this.imagen;
            }
            Categoria seleccionado = (Categoria) cboCategoria.getSelectedItem();
            res = this.control.actualizar(
                    Integer.parseInt(id), textNombre.getText(), this.nombreAnt, seleccionado.getId(), textCodigo.getText(), Double.parseDouble(textPrecio.getText()), Integer.parseInt(textStock.getText()), textDescripcion.getText(), imagenActual);
            this.tabCrud.setEnabledAt(1, false);
            this.tabCrud.setEnabledAt(0, true);
            this.tabCrud.setSelectedIndex(0);
        } else {

            Categoria seleccionado = (Categoria) cboCategoria.getSelectedItem();
            res = this.control.insertar(
                    seleccionado.getId(), textCodigo.getText(), textNombre.getText(), Double.parseDouble(textPrecio.getValue().toString()), Integer.parseInt(this.textStock.getText()), textDescripcion.getText(), this.imagen);
        }

        if (res.equals("OK")) {

            if (!this.imagen.equals("")) {
                this.subirImagenes();
            }

            this.mensajeSuccess("Registrado correctamente.");
            this.limpiarFormulario();
            this.tabla.clearSelection();
            this.listar("",false);
        } else {
            this.mensajeError(res);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        if (id.length() > 0) {

            this.tabCrud.setEnabledAt(0, false);
            this.tabCrud.setEnabledAt(1, true);
            this.tabCrud.setSelectedIndex(1);
            this.accion = "EDITAR";
            this.btnGuardar.setText("Editar");

        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        // TODO add your handling code here:
        if (this.id.length() > 0) {
            if (JOptionPane.showConfirmDialog(this, "¿Desea desactivar el registro: " + nombreAnt + " ?", "Desactivar", JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
                String res = this.control.desactivar(Integer.parseInt(id));
                if (res.equals("OK")) {
                    this.listar("",false);
                } else {
                    this.mensajeError(res);
                }

            }
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        if (this.id.length() > 0) {
            if (JOptionPane.showConfirmDialog(this, "¿Desea activar el registro: " + nombreAnt + " ?", "Activar", JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
                String res = this.control.activar(Integer.parseInt(id));
                if (res.equals("OK")) {
                    this.listar("",false);
                } else {
                    this.mensajeError(res);
                }
            }
        }
    }//GEN-LAST:event_btnActivarActionPerformed
    private void subirImagenes() {
        File origen = new File(this.rutaOrigen);
        File destino = new File(this.rutaDestino);
        try {
            InputStream in = new FileInputStream(origen);
            OutputStream out = new FileOutputStream(destino);
            byte[] buf = new byte[1024];
            int len;
            while ((len = in.read(buf)) > 0) {
                out.write(buf, 0, len);
            }
            in.close();
            out.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        int estado = file.showOpenDialog(this);
        if (estado == JFileChooser.APPROVE_OPTION) {
            this.imagen = file.getSelectedFile().getName();
            this.rutaOrigen = file.getSelectedFile().getAbsolutePath();
            this.rutaDestino = this.DIRECTORIO + this.imagen;

            ImageIcon im = new ImageIcon(this.rutaOrigen);
            Icon icono = new ImageIcon(im.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            lblImagen.setText(null);
            lblImagen.setIcon(icono);
            lblImagen.repaint();
        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void cboTotalPorPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTotalPorPaginaActionPerformed
        // TODO add your handling code here:
        this.paginar();
    }//GEN-LAST:event_cboTotalPorPaginaActionPerformed

    private void cboNumPaginaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNumPaginaItemStateChanged
        // TODO add your handling code here:
       
        if ( evt.getStateChange() == java.awt.event.ItemEvent.SELECTED &&this.primeraCarga==false){
             System.out.println("Selectttt");
            this.listar("",true);
        }
    }//GEN-LAST:event_cboNumPaginaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JComboBox<Categoria> cboCategoria;
    private javax.swing.JComboBox<String> cboNumPagina;
    private javax.swing.JComboBox<String> cboTotalPorPagina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTotalRegistros;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTabbedPane tabCrud;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JFormattedTextField textPrecio;
    private javax.swing.JFormattedTextField textStock;
    // End of variables declaration//GEN-END:variables

    private void listenerEdit() {
        ListSelectionModel selectionModel = tabla.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    boolean filaSeleccionada = !selectionModel.isSelectionEmpty() && tabla.getSelectedRowCount() == 1;

                    btnEditar.setEnabled(filaSeleccionada);
                    btnDesactivar.setEnabled(false);
                    btnActivar.setEnabled(false);
                  
                    if (filaSeleccionada) {
                        int filaSeleccionadaIndex = tabla.getSelectedRow();

                        id = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 0));
                        int categoriaId = Integer.parseInt(String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 1)));
                        String categoriaNombre = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 2));
                        String codigo = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 3));
                        String nombre = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 4));
                        nombreAnt = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 4));
                        String precio = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 5));
                        String stock = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 6));
                        String descripcion = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 7));
                        imagenAnt = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 8));
                        String estado = String.valueOf(tabla.getValueAt(filaSeleccionadaIndex, 9));

                        Categoria seleccionado = new Categoria(categoriaId, categoriaNombre);

                        cboCategoria.setSelectedItem(seleccionado);
                        textCodigo.setText(codigo);
                        textNombre.setText(nombre);
                        textPrecio.setText(precio);
                        textStock.setText(stock);
                        textDescripcion.setText(descripcion);
                        if (!imagenAnt.isEmpty()) {
                            ImageIcon im = new ImageIcon(DIRECTORIO + imagenAnt);
                            Icon icono = new ImageIcon(im.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
                            lblImagen.setIcon(icono);
                            lblImagen.repaint();
                        }

                        if (estado.equals("Activo")) {
                            btnDesactivar.setEnabled(true);

                        }
                        if (estado.equals("Inactivo")) {
                            btnActivar.setEnabled(true);
                        }

                    }
                }

            }
        });

    }

    private void ocultarColumnas() {
        this.tabla.getColumnModel().getColumn(1).setMaxWidth(0);
        this.tabla.getColumnModel().getColumn(1).setMinWidth(0);
        this.tabla.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        this.tabla.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
    }
    private void paginar(){
        int totalPaginas;
        
        this.totalRegistros=this.control.total();
        this.totalPorPagina=Integer.parseInt((String)cboTotalPorPagina.getSelectedItem());
        totalPaginas=(int)(Math.ceil((double)this.totalRegistros/this.totalPorPagina));
        if (totalPaginas==0){
            totalPaginas=1;
        }
        cboNumPagina.removeAllItems();
        
        for (int i = 1; i <= totalPaginas; i++) {
            cboNumPagina.addItem(Integer.toString(i));
        }
        cboNumPagina.setSelectedIndex(0);
    }
    private void listar(String text, boolean paginar) {
        
         this.totalPorPagina=Integer.parseInt((String)cboTotalPorPagina.getSelectedItem());
        if ((String)cboNumPagina.getSelectedItem()!=null){
            this.numPagina=Integer.parseInt((String)cboNumPagina.getSelectedItem());
        }
        
        if (paginar==true){
            tabla.setModel(this.control.listar(text,this.totalPorPagina,this.numPagina));
        }else{
            tabla.setModel(this.control.listar(text,this.totalPorPagina,1));
        }
        
        //this.tabla.setModel(this.control.listar(text, totalPorPagina, numPagina));
        TableRowSorter orden = new TableRowSorter(this.tabla.getModel());
        this.tabla.setRowSorter(orden);
        ocultarColumnas();
        this.labelTotalRegistros.setText("Mostrando " + this.control.totalMostrados() + " de " + this.control.total());

    }

    private void cargarCategorias() {
        DefaultComboBoxModel<Categoria> items = this.control.seleccionar();
        cboCategoria.setModel(items);
    }

    private void mensajeError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeWarning(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Sistema", JOptionPane.WARNING_MESSAGE);
    }

    private void mensajeSuccess(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }

    private void limpiarFormulario() {
        this.textBuscar.setText("");

        this.id = "";
        this.nombreAnt = "";
        this.btnGuardar.setText("Guardar");
        this.textCodigo.setText("");
        this.textNombre.setText("");
        this.textDescripcion.setText("");
        this.textPrecio.setText("");
        this.textStock.setText("");
        this.imagen = "";
        this.imagenAnt = "";
        this.lblImagen.setIcon(null);
        this.rutaDestino = "";
        this.rutaOrigen = "";
        this.accion = "guardar";

    }

}
